#    _____ _                    _        ______
#  / ____|(_)                  | |      |  ____|
# | (___   _  _ __ ___   _ __  | |  ___ | |__  _ __  ___   ___  ____ ___
#  \___ \ | || '_ ` _ \ | '_ \ | | / _ \|  __|| '__|/ _ \ / _ \|_  // _ \
#  ____) || || | | | | || |_) || ||  __/| |   | |  |  __/|  __/ / /|  __/
# |_____/ |_||_| |_| |_|| .__/ |_| \___||_|   |_|   \___| \___|/___|\___|
#                       | |
#                       |_|

#You can add a line break to strings using '\n'
#You can add colors and/or text variants using standard minecraft color codes for example: "§c"

#Makes sure players are always teleported to the ground when getting frozen, however this does mean they get teleported to the surface when in a cave for example.
safeLocation: true

#Customize the message a player receives upon trying to use a command whilst frozen.
playerCommandMessage: "You are frozen and now unable to send commands, if you want to reach staff you can type in chat, only staff members can see your messages."

#This is the message the player will see upon being frozen or trying to move.
playerFreezeMessage: "\n§l§cATTENTION!\n§c\nYou have been frozen! join discord.gg/vanarchy\nIf you log out you will be BANNED.\n"
#Add gray lines above and bellow the freeze message.
playerFreezeMessageLines: true

#When a player gets frozen this message will appear in their screen
freezeTitle: true
primaryFreezeMessage: "§cYou have been frozen!"
secondaryFreezeMessage: "§5Join Discord.gg/Vanarchy"
#These variables determine the amount of time the message will appear, stay and leave. The values are measured in ticks. 20 ticks is equal to 1 second.
fadeIn: 0
stay: 800000000
fadeOut: 0