
#    _____ _                    _        ______
#  / ____|(_)                  | |      |  ____|
# | (___   _  _ __ ___   _ __  | |  ___ | |__  _ __  ___   ___  ____ ___
#  \___ \ | || '_ ` _ \ | '_ \ | | / _ \|  __|| '__|/ _ \ / _ \|_  // _ \
#  ____) || || | | | | || |_) || ||  __/| |   | |  |  __/|  __/ / /|  __/
# |_____/ |_||_| |_| |_|| .__/ |_| \___||_|   |_|   \___| \___|/___|\___|
#                       | |
#                       |_|


#Makes sure players are always teleported to the ground when getting frozen, however this does mean they get teleported to the surface when in a cave for example.
safeLocation: true