name: SimpleFreeze
version: '${project.version}'
main: dev.boostio.SimpleFreeze
api-version: 1.18
authors: [ Boostio, Bram ]

commands:
  freeze:
    description: A command to freeze a player!
    permission: SimpleFreeze.use
    permission-message: Unknown command. Type "/help" for help
    aliases:
      - ss
permissions:
  SimpleFreeze.use:
    description: Allows the player to use the /freeze command.
    default: op
  SimpleFreeze.bypass:
    description: Prevents the player from being frozen.
    default: op